# Makefile generated by imake - do not edit!
# $XConsortium: imake.c,v 1.65 91/07/25 17:50:17 rws Exp $
#
# The cpp used on this machine replaces all newlines and multiple tabs and
# spaces in a macro expansion with a single space.  Imake tries to compensate
# for this, but is not always successful.
#

SUFFIX=.
UPFIX=.

SUBDIRS=src doc

SHELL=/bin/sh

TARGETARCH=sun4
TARGETOS=solaris1

TARGETCC=gcc
TARGETCPLUS=g++
C=$(TARGETCC)
CC=$(TARGETCC)
CPLUS=$(TARGETCPLUS)

TARGET=$(TARGETARCH).$(TARGETOS).$(TARGETCPLUS)

TARGETSHORT=$(TARGETARCH)
TARGETSHORT2=$(TARGETARCH).$(TARGETOS)

SYSPREFIX=tps

SYSMAJOR=2
SYSMINOR=1
SYSPATCHLEVEL=c

SYSVERSION=$(SYSMAJOR).$(SYSMINOR)

SYSNAME=$(SYSPREFIX)$(SYSVERSION)

SYSFULLNAME=$(SYSNAME)$(SYSPATCHLEVEL)

SYSHOME=/tmp_mnt/cs/research/arcadia/csci7818/dennis/tps2.1

MAKE=make
AR=ar
ARFLAGS=cru

RANLIB=ranlib
RANLIBT=touch

MKDIRS=mkdir -p

IMAKE=imake
MAKEDEPEND=makedepend

SYSTARGET=$(SYSHOME)/$(TARGET)
SYSBIN=$(SYSTARGET)/bin
SYSLIBDIR=$(SYSTARGET)/lib
SYSINCLUDES=$(SYSTARGET)/include

SYSTARGETSHORT=$(SYSHOME)/$(TARGETSHORT)
SYSTARGETSHORT2=$(SYSHOME)/$(TARGETSHORT2)

STAR=*

SRCTARNAME=$(SYSFULLNAME).tar

THISDIRREL=$(UPFIX)/$(SUFFIX)
THISDIRABS=$(SYSHOME)/$(SUFFIX)

SRCTARLIST=$(THISDIRABS)/INVENTORY

TARPREFIX=$(SUFFIX)

All: all

propagate:
	@-for i in $(SUBDIRS); do ( cd $$i; echo '<entering' $$i; $(CMD) ; echo '>leaving' $$i ;cd .. ); done

imakeall:
	make propagate CMD='$(IMAKE); $(MAKE) imakeall'

tagversion:
	make propagate CMD='$(MAKE) tagversion'

all:
	make propagate CMD='$(MAKE) all'

depend:
	make propagate CMD='$(MAKE) depend'

install:
	make propagate CMD='$(MAKE) install'

clean:
	make propagate CMD='$(MAKE) clean'

Clean:
	make propagate CMD='$(MAKE) Clean'

RCS:
	make propagate CMD='$(MAKE) RCS'

##################################################
# Define the local files to be used in tars and version construction

SUPPORTDIRS=

IMAKEFILES=Imakefile Imake.tmpl Config.Imake

MISCFILES=README INSTALL CHANGES INVENTORY platform

LOCALFILES=$(IMAKEFILES) $(MISCFILES) $(SUPPORTDIRS)

##################################################
# Provide tar for distribution

srctar:
	tar -cf $(SRCTARNAME) -I INVENTORY

CUFTP=/cs/ftp/distribs/arcadia
cuftp: $(SRCTARNAME)
	       compress < $(SRCTARNAME) >$(CUFTP)/$(SRCTARNAME).Z
	       cp $(SYSPREFIX).txt $(CUFTP)/$(SYSFULLNAME).txt

