/*
 * Copyright (c) 1993 Dennis Heimbigner
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "Sysdep.H"
#include "chartab.H"

unsigned int Tps_chartable[256] = {
/*[^@]*/ (TPSC_WS),
/*[^A]*/ (TPSC_WS),
/*[^B]*/ (TPSC_WS),
/*[^C]*/ (TPSC_WS),
/*[^D]*/ (TPSC_WS),
/*[^E]*/ (TPSC_WS),
/*[^F]*/ (TPSC_WS),
/*[^G]*/ (TPSC_WS),
/*[^H]*/ (TPSC_WS),
/*[^I]*/ (TPSC_WS),
/*[^J]*/ (TPSC_WS | TPSC_EOL),
/*[^K]*/ (TPSC_WS),
/*[^L]*/ (TPSC_WS),
/*[^M]*/ (TPSC_WS),
/*[^N]*/ (TPSC_WS),
/*[^O]*/ (TPSC_WS),
/*[^P]*/ (TPSC_WS),
/*[^Q]*/ (TPSC_WS),
/*[^R]*/ (TPSC_WS),
/*[^S]*/ (TPSC_WS),
/*[^T]*/ (TPSC_WS),
/*[^U]*/ (TPSC_WS),
/*[^V]*/ (TPSC_WS),
/*[^W]*/ (TPSC_WS),
/*[^X]*/ (TPSC_WS),
/*[^Y]*/ (TPSC_WS),
/*[^Z]*/ (TPSC_WS),
/*[^[]*/ (TPSC_WS),
/*[^\]*/ (TPSC_WS),
/*[^]]*/ (TPSC_WS),
/*[^^]*/ (TPSC_WS),
/*[^_]*/ (TPSC_WS),
/*[ ]*/ (TPSC_WS | TPSC_PRINTABLE),
/*[!]*/ (TPSC_SPECIAL | TPSC_PRINTABLE),
/*["]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[#]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[$]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[%]*/ (TPSC_SPECIAL | TPSC_PRINTABLE),
/*[&]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[']*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[(]*/ (TPSC_SPECIAL | TPSC_PRINTABLE),
/*[)]*/ (TPSC_SPECIAL | TPSC_PRINTABLE),
/*[*]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[+]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[,]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[-]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[.]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[/]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[0]*/ (TPSC_HEXDIGIT | TPSC_OCTDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[1]*/ (TPSC_HEXDIGIT | TPSC_OCTDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[2]*/ (TPSC_HEXDIGIT | TPSC_OCTDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[3]*/ (TPSC_HEXDIGIT | TPSC_OCTDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[4]*/ (TPSC_HEXDIGIT | TPSC_OCTDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[5]*/ (TPSC_HEXDIGIT | TPSC_OCTDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[6]*/ (TPSC_HEXDIGIT | TPSC_OCTDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[7]*/ (TPSC_HEXDIGIT | TPSC_OCTDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[8]*/ (TPSC_HEXDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[9]*/ (TPSC_HEXDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[:]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[;]*/ (TPSC_SPECIAL | TPSC_PRINTABLE),
/*[<]*/ (TPSC_SPECIAL | TPSC_PRINTABLE),
/*[=]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[>]*/ (TPSC_SPECIAL | TPSC_PRINTABLE),
/*[?]*/ (TPSC_SPECIAL | TPSC_PRINTABLE),
/*[@]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[A]*/ (TPSC_HEXDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[B]*/ (TPSC_HEXDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[C]*/ (TPSC_HEXDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[D]*/ (TPSC_HEXDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[E]*/ (TPSC_HEXDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[F]*/ (TPSC_HEXDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[G]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[H]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[I]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[J]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[K]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[L]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[M]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[N]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[O]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[P]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[Q]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[R]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[S]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[T]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[U]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[V]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[W]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[X]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[Y]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[Z]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[[]*/ (TPSC_SPECIAL | TPSC_PRINTABLE),
/*[\]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[]]*/ (TPSC_SPECIAL | TPSC_PRINTABLE),
/*[^]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[_]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[`]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[a]*/ (TPSC_HEXDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[b]*/ (TPSC_HEXDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[c]*/ (TPSC_HEXDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[d]*/ (TPSC_HEXDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[e]*/ (TPSC_HEXDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[f]*/ (TPSC_HEXDIGIT | TPSC_NAME | TPSC_PRINTABLE),
/*[g]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[h]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[i]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[j]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[k]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[l]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[m]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[n]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[o]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[p]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[q]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[r]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[s]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[t]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[u]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[v]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[w]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[x]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[y]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[z]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[{]*/ (TPSC_SPECIAL | TPSC_PRINTABLE),
/*[ | ]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[}]*/ (TPSC_SPECIAL | TPSC_PRINTABLE),
/*[~]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[^?]*/ (TPSC_NAME | TPSC_PRINTABLE),
/*[\200]*/ (TPSC_WS),
/*[\201]*/ (TPSC_WS),
/*[\202]*/ (TPSC_WS),
/*[\203]*/ (TPSC_WS),
/*[\204]*/ (TPSC_WS),
/*[\205]*/ (TPSC_WS),
/*[\206]*/ (TPSC_WS),
/*[\207]*/ (TPSC_WS),
/*[\210]*/ (TPSC_WS),
/*[\211]*/ (TPSC_WS),
/*[\212]*/ (TPSC_WS),
/*[\213]*/ (TPSC_WS),
/*[\214]*/ (TPSC_WS),
/*[\215]*/ (TPSC_WS),
/*[\216]*/ (TPSC_WS),
/*[\217]*/ (TPSC_WS),
/*[\220]*/ (TPSC_WS),
/*[\221]*/ (TPSC_WS),
/*[\222]*/ (TPSC_WS),
/*[\223]*/ (TPSC_WS),
/*[\224]*/ (TPSC_WS),
/*[\225]*/ (TPSC_WS),
/*[\226]*/ (TPSC_WS),
/*[\227]*/ (TPSC_WS),
/*[\230]*/ (TPSC_WS),
/*[\231]*/ (TPSC_WS),
/*[\232]*/ (TPSC_WS),
/*[\233]*/ (TPSC_WS),
/*[\234]*/ (TPSC_WS),
/*[\235]*/ (TPSC_WS),
/*[\236]*/ (TPSC_WS),
/*[\237]*/ (TPSC_WS),
/*[\240]*/ (TPSC_WS),
/*[\241]*/ (TPSC_WS),
/*[\242]*/ (TPSC_WS),
/*[\243]*/ (TPSC_WS),
/*[\244]*/ (TPSC_WS),
/*[\245]*/ (TPSC_WS),
/*[\246]*/ (TPSC_WS),
/*[\247]*/ (TPSC_WS),
/*[\250]*/ (TPSC_WS),
/*[\251]*/ (TPSC_WS),
/*[\252]*/ (TPSC_WS),
/*[\253]*/ (TPSC_WS),
/*[\254]*/ (TPSC_WS),
/*[\255]*/ (TPSC_WS),
/*[\256]*/ (TPSC_WS),
/*[\257]*/ (TPSC_WS),
/*[\260]*/ (TPSC_WS),
/*[\261]*/ (TPSC_WS),
/*[\262]*/ (TPSC_WS),
/*[\263]*/ (TPSC_WS),
/*[\264]*/ (TPSC_WS),
/*[\265]*/ (TPSC_WS),
/*[\266]*/ (TPSC_WS),
/*[\267]*/ (TPSC_WS),
/*[\270]*/ (TPSC_WS),
/*[\271]*/ (TPSC_WS),
/*[\272]*/ (TPSC_WS),
/*[\273]*/ (TPSC_WS),
/*[\274]*/ (TPSC_WS),
/*[\275]*/ (TPSC_WS),
/*[\276]*/ (TPSC_WS),
/*[\277]*/ (TPSC_WS),
/*[\300]*/ (TPSC_WS),
/*[\301]*/ (TPSC_WS),
/*[\302]*/ (TPSC_WS),
/*[\303]*/ (TPSC_WS),
/*[\304]*/ (TPSC_WS),
/*[\305]*/ (TPSC_WS),
/*[\306]*/ (TPSC_WS),
/*[\307]*/ (TPSC_WS),
/*[\310]*/ (TPSC_WS),
/*[\311]*/ (TPSC_WS),
/*[\312]*/ (TPSC_WS),
/*[\313]*/ (TPSC_WS),
/*[\314]*/ (TPSC_WS),
/*[\315]*/ (TPSC_WS),
/*[\316]*/ (TPSC_WS),
/*[\317]*/ (TPSC_WS),
/*[\320]*/ (TPSC_WS),
/*[\321]*/ (TPSC_WS),
/*[\322]*/ (TPSC_WS),
/*[\323]*/ (TPSC_WS),
/*[\324]*/ (TPSC_WS),
/*[\325]*/ (TPSC_WS),
/*[\326]*/ (TPSC_WS),
/*[\327]*/ (TPSC_WS),
/*[\330]*/ (TPSC_WS),
/*[\331]*/ (TPSC_WS),
/*[\332]*/ (TPSC_WS),
/*[\333]*/ (TPSC_WS),
/*[\334]*/ (TPSC_WS),
/*[\335]*/ (TPSC_WS),
/*[\336]*/ (TPSC_WS),
/*[\337]*/ (TPSC_WS),
/*[\340]*/ (TPSC_WS),
/*[\341]*/ (TPSC_WS),
/*[\342]*/ (TPSC_WS),
/*[\343]*/ (TPSC_WS),
/*[\344]*/ (TPSC_WS),
/*[\345]*/ (TPSC_WS),
/*[\346]*/ (TPSC_WS),
/*[\347]*/ (TPSC_WS),
/*[\350]*/ (TPSC_WS),
/*[\351]*/ (TPSC_WS),
/*[\352]*/ (TPSC_WS),
/*[\353]*/ (TPSC_WS),
/*[\354]*/ (TPSC_WS),
/*[\355]*/ (TPSC_WS),
/*[\356]*/ (TPSC_WS),
/*[\357]*/ (TPSC_WS),
/*[\360]*/ (TPSC_WS),
/*[\361]*/ (TPSC_WS),
/*[\362]*/ (TPSC_WS),
/*[\363]*/ (TPSC_WS),
/*[\364]*/ (TPSC_WS),
/*[\365]*/ (TPSC_WS),
/*[\366]*/ (TPSC_WS),
/*[\367]*/ (TPSC_WS),
/*[\370]*/ (TPSC_WS),
/*[\371]*/ (TPSC_WS),
/*[\372]*/ (TPSC_WS),
/*[\373]*/ (TPSC_WS),
/*[\374]*/ (TPSC_WS),
/*[\375]*/ (TPSC_WS),
/*[\376]*/ (TPSC_WS),
/*[\377]*/ (TPSC_WS)
};
